name: any_image_view
version: 2.0.1

description: "A versatile Flutter image viewer supporting PNG, JPG, WebP, GIF, TIFF, RAW, SVG, Lottie, XFile, and network images with best resolution â€” all in one seamless package."
topics:
  - flutter
  - image
  - image-viewer
  - svg
  - lottie

homepage: https://farhansadikgalib.com/
repository: https://github.com/farhansadikgalib/any_image_view/blob/main/README.md
issue_tracker: https://github.com/farhansadikgalib/any_image_view/issues

screenshots:
  - description: "any image view"
    path: raw/ss.png

environment:
  sdk: ^3.2.6
  flutter: ">=3.10.0"

dependencies:
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  cross_file: ^0.3.5+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
